<main>
    <form action="index.php?route=check_create_user" method="POST">
        <fieldset>
            <label for="email">E-Mail</label>
            <input type="mail" name="email" id="email"/>
        </fieldset>
        <fieldset>
            <label for="first_name">Prenom</label>
            <input type="text" name="first_name" id="first_name"/>
        </fieldset>
        <fieldset>
            <label for="emlastnameail">Nom</label>
            <input type="text" name="last_name" id="last_name"/>
        </fieldset>
        <input type="submit" name="submit" value="Soumettre"/>
    </form>
</main>