<main>
    <section>
        <h2>Quel est votre nom, héros ?</h2>
        <div>
           
            <form method="get" action="index.php">
                <div>
                    <input type="text" name="heroName" id="heroName" required />
                </div>
                <div>
                    <input type="hidden" name="route" value="choice" /> 
                    <input type="submit" value="Commencer votre aventure" />
                </div>
            </form>
        </div>
    </section>
    <section>
        <section>
            <img src="assets/img/cross-swords.png" />
            <h1>Le site dont vous êtes le héros</h1>
        </section>
    </section>
</main>
