<main>
    <section>
        <h2>Bonjour <?= htmlspecialchars($playerName) ?>, faites votre choix :</h2> 
        <div>
            <form method="get" action="controllers/user-form.php">
                <div>
                    <input type="radio" id="choice-1" name="choice" value="choice-1">
                    <label for="choice-1">Choix 1</label>
                </div>
                <div>
                    <input type="radio" id="choice-2" name="choice" value="choice-2">
                    <label for="choice-2">Choix 2</label>
                </div>
                <div>
                    <input type="radio" id="choice-3" name="choice" value="choice-3">
                    <label for="choice-3">Choix 3</label>
                </div>
                <div>
                    <input type="submit" value="Valider le choix" />
                </div>
            </form>
        </div>
    </section>
    <section>
        <section>
            <img src="assets/img/door.png" />
            <h1>Description de la situation, blablabl magicien, blablabla</h1>
        </section>
    </section>
</main>
