<?php

?>
<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=show_user">Utilisateurs</a>
					</li>
					<li>
					    <a href="index.php?route=create_user">Crée</a>
					</li> 
					<li>
					    <a href="index.php?route=">Liste</a>
					</li>
				</ul>
			</nav>
		</header>
		<?php
			if($route === "show_user")
			{
			    require "users/show.phtml";
			} elseif($route === "create_user")
			{
			    require "users/create.phtml";
			} elseif($route === "update_user")
			{
			    require "users/update.phtml";
			} else
			{
			    require "users/list.phtml";
			}
		?>
	</body>
</html>