<!DOCTYPE html>
<html lang="fr">
	<head>
		<meta charset="utf-8" />
		<title>Exercice Routeur MVC</title>
	</head>
	<body>
		<header>
			<nav>
				<ul>
					<li>
						<a href="index.php">Accueil</a>
					</li>
					<li>
						<a href="index.php?route=create_user">Create User</a>
					</li>
					<li>
					    <a href="index.php?route=show_user">Show user</a>
					</li> 
				</ul>
			</nav>
		</header>
		<?php
			if($route === "create_user")
			{
			    require "users/create.phtml";
			} elseif($route === "show_user")
			{
			    require "users/list.phtml";
			} else
			{
			    require_once __DIR__."/../index.php";
			}
		?>
	</body>
</html>