
<?php

if (isset($_SESSION['user'])) {
  $firstName = $_SESSION['user']['first_name'];
  $lastName = $_SESSION['user']['last_name'];

  echo <<<HTML
    <br />
    <h1>Bonjour, $firstName $lastName !</h1>
    <br /><br />
    <a href="logic/logout.php">Deconnexion</a>
  HTML;
} else {

  echo <<<HTML
    <br />
    <a href="index.php?route=inscription">Inscription</a>
    <br /><br />
    <a href="index.php?route=connexion">Connexion</a>
  HTML;
}
?>