<?php



?>

<!DOCTYPE html>
<html lang="fr">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Exercice Auth</title>
</head>

<body>
  <?php
  global $route;
  switch ($route) {
    case "inscription":
      require "register.phtml";
      break;
    case "connexion":
      require "login.phtml";
      break;
    default:
      require "home.phtml";
  }
  ?>
</body>

</html>