<main>
    <form method="POST" action="index.php?route=check_create_user">
        <fieldset>
            <label for="first_name">Prénom</label>
            <input type="text" name="first_name" id="first_name"/>
        </fieldset>
        <fieldset>
            <label for="last_name">Nom</label>
            <input type="text" name="last_name" id="last_name"/>
        </fieldset>
        <fieldset>
            <label for="email">E-mail</label>
            <input type="mail" name="email" id="email"/>
        </fieldset>
    </form>
</main>