<main>
   <h1>Modifier l'utilisateur</h1>
    <form action="/index.php?action=updateUser&id=<?= htmlspecialchars($user->getId()) ?>" method="POST">
        <label for="first_name">Prénom :</label>
        <input type="text" id="first_name" name="first_name" value="<?= htmlspecialchars($user->getFirstName()) ?>" required>
        <br>
        <label for="last_name">Nom :</label>
        <input type="text" id="last_name" name="last_name" value="<?= htmlspecialchars($user->getLastName()) ?>" required>
        <br>
        <label for="email">Email :</label>
        <input type="email" id="email" name="email" value="<?= htmlspecialchars($user->getEmail()) ?>" required>
        <br>
        <button type="submit">Enregistrer</button>
    </form>
    <a href="/index.php?action=listUsers">Annuler</a>
</main>